import fs from "fs";

interface FontInfo {
    name: string;
    type: "serif" | "sans-serif" | "monospace";
    supportedLanguages: Array<keyof typeof LANGUAGE_TABLE>;
    mainUse: Array<keyof typeof USE_TABLE>;
    supportVariableFont: boolean;
    license: keyof typeof LICENSE_TABLE | { name: "Proprietary"; url: string };
    website: `https://${string}`;
}

const LANGUAGE_TABLE = {
    ja: "日本語",
    en: "英語"
} as const;

const USE_TABLE = {
    document: "文書",
    design: "デザイン",
    coding: "コーディング"
} as const;

const LICENSE_TABLE = {
    "OFL1.1": {
        name: "SIL Open Font License 1.1",
        url: "https://openfontlicense.org/open-font-license-official-text/"
    }
} as const;

const fontCollection = [
    {
        name: "Noto Sans JP",
        type: "sans-serif",
        supportedLanguages: ["ja"],
        mainUse: ["document", "design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://fonts.google.com/noto/specimen/Noto+Sans+JP"
    },
    {
        name: "Noto Serif JP",
        type: "serif",
        supportedLanguages: ["ja"],
        mainUse: ["document", "design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://fonts.google.com/noto/specimen/Noto+Sans+JP"
    },
    {
        name: "Monaspace",
        type: "monospace",
        supportedLanguages: ["en"],
        mainUse: ["coding"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://monaspace.githubnext.com/"
    },
    {
        name: "Moralerspace",
        type: "monospace",
        supportedLanguages: ["ja"],
        mainUse: ["coding"],
        supportVariableFont: false,
        license: "OFL1.1",
        website: "https://github.com/yuru7/moralerspace"
    },
    {
        name: "JetBrains Mono",
        type: "monospace",
        supportedLanguages: ["en"],
        mainUse: ["coding", "design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://www.jetbrains.com/ja-jp/lp/mono/"
    },
    {
        name: "League Spartan",
        type: "sans-serif",
        supportedLanguages: ["en"],
        mainUse: ["design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://www.theleagueofmoveabletype.com/league-spartan"
    },
    {
        name: "League Mono",
        type: "monospace",
        supportedLanguages: ["en"],
        mainUse: ["coding", "design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://www.theleagueofmoveabletype.com/league-mono"
    },
    {
        name: "Mona Sans",
        type: "sans-serif",
        supportedLanguages: ["en"],
        mainUse: ["design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://github.com/mona-sans"
    },
    {
        name: "カッティングエッジ",
        type: "sans-serif",
        supportedLanguages: ["ja"],
        mainUse: ["design"],
        supportVariableFont: false,
        license: {
            name: "Proprietary",
            url: "https://flopdesign.booth.pm/items/7152721"
        },
        website: "https://flopdesign.booth.pm/items/7152721"
    },
    {
        name: "Google Sans",
        type: "sans-serif",
        supportedLanguages: ["en"],
        mainUse: ["document", "design"],
        supportVariableFont: true,
        license: "OFL1.1",
        website: "https://fonts.google.com/specimen/Google+Sans"
    }
] as const satisfies FontInfo[];

const fontCollectionText = fontCollection
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((font) => {
        return `
### ${font.name}

- 🖋️種類：\`${font.type}\`
- 💬対応言語：${font.supportedLanguages
            .map((lang) => LANGUAGE_TABLE[lang])
            .sort()
            .join(", ")}
- 💡主な用途：${font.mainUse
            .map((use) => USE_TABLE[use])
            .sort()
            .join(", ")}
- ⚙️可変フォント：${font.supportVariableFont ? "対応" : "非対応"}
- 📜ライセンス：[${typeof font.license === "string" ? LICENSE_TABLE[font.license].name : font.license.name}](${typeof font.license === "string" ? LICENSE_TABLE[font.license].url : font.license.url})
- 🌐公式サイト：[リンク](${font.website})
    `.trim();
    });

const result =
    `
<!-- This file is generated by script/generate.ts. Do not edit this file directly. -->

# ✨Font Collection

お気に入りのフォントたち。

## 📚フォント一覧

${fontCollectionText.join("\n\n")}

## 💻開発

\`README.md\`は、\`script/generate.ts\`から生成されます。これを実行するには、次のコマンドを入力します。

\`\`\`sh
npm run generate
\`\`\`
`.trim() + "\n";

fs.writeFileSync("README.md", result);
